version: "2"

services:
  docker_fn_download:
    build: .
    # with the following line, an alternativ python app could be started
    # command: python3 sonosServer.py 
    volumes:
      - ./code:/code

